project_id = "habesha-nights"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[storage]
enabled = true
file_size_limit = "5MiB"
